### ISSUE TITLE
dependency issue for nginx chart

### ISSUE THREAD

**Issue by JuliusDigel** [xerrni/scancode-kube#2]
when installing the chart my source controller is throwing the following error:

"error":"dependency build error: failed to add remote dependency 'nginx': failed to get chart 'nginx' version '9.x.x' from 'https://charts.bitnami.com/bitnami': no 'nginx' chart with version matching '9.x.x' found"}

could you please update the version to a more recent one? 

[~/scancode-kube/charts/scancode/Chart.yaml](https://github.com/xerrni/scancode-kube/blob/master/charts/scancode/Chart.yaml)

```
dependencies:
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
```

Thank you very much for creating and maintaining this helm-chart!
